[project]
name = "analysis-default-of-credit-card-clients"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.4",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
    "tabulate>=0.9.0",
    "xlrd>=2.0.2",
]
